import "./globals.css";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokProvider from "../components/StoryblokProvider";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
const token = process.env.NEXT_PUBLIC_STORYBLOK_API_TOKEN;

storyblokInit({
  accessToken: token,
  use: [apiPlugin],
  apiOptions: {
    region: "us",
  },
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutType {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body>
          <Navigation />
          {children}
          <Footer />
        </body>
      </html>
    </StoryblokProvider>
  );
}
